export const ITEM_REQUEST = "ITEM_REQUEST";
export const ITEM_SUCCESS = "ITEM_SUCCESS";
export const ITEM_FAIL = "ITEM_FAIL";

export const ITEM_ADD_REQUEST = "ITEM_ADD_REQUEST";
export const ITEM_ADD_SUCCESS = "ITEM_ADD_SUCCESS";
export const ITEM_ADD_FAIL = "ITEM_ADD_FAIL";
export const ITEM_ADD_RESET = "ITEM_ADD_FAIL";

export const ITEM_DELETE_REQUEST = "ITEM_DELETE_REQUEST";
export const ITEM_DELETE_SUCCESS = "ITEM_DELETE_SUCCESS";
export const ITEM_DELETE_FAIL = "ITEM_DELETE_FAIL";
export const ITEM_DELETE_RESET = "ITEM_DELETE_RESET";

export const ITEM_EDIT_REQUEST = "ITEM_EDIT_REQUEST";
export const ITEM_EDIT_SUCCESS = "ITEM_EDIT_SUCCESS";
export const ITEM_EDIT_FAIL = "ITEM_EDIT_FAIL";
export const ITEM_EDIT_RESET = "ITEM_EDIT_RESET";

export const ITEM_CHECK_REQUEST = "ITEM_CHECK_REQUEST";
export const ITEM_CHECK_SUCCESS = "ITEM_CHECK_SUCCESS";
export const ITEM_CHECK_FAIL = "ITEM_CHECK_FAIL";
export const ITEM_CHECK_RESET = "ITEM_CHECK_RESET";
