export const LISTS_REQUEST = "LISTS_REQUEST";
export const LISTS_SUCCESS = "LISTS_SUCCESS";
export const LISTS_FAIL = "LISTS_FAIL";

export const LIST_REQUEST = "LIST_REQUEST";
export const LIST_SUCCESS = "LIST_SUCCESS";
export const LIST_FAIL = "LIST_FAIL";

export const LIST_CREATE_REQUEST = "LIST_CREATE_REQUEST";
export const LIST_CREATE_SUCCESS = "LIST_CREATE_SUCCESS";
export const LIST_CREATE_FAIL = "LIST_CREATE_FAIL";
